const ogCharacters = [
    {
        name: "Ana",
        imageSrc: "./characters/images/ana.png",
        role: "Support"
    }, {
        name: "Ashe",
        imageSrc: "./characters/images/ashe.png",
        role: "Damage"
    }, {
        name: "Baptiste",
        imageSrc: "./characters/images/baptiste.png",
        role: "Support"
    }, {
        name: "Bastion",
        imageSrc: "./characters/images/bastion.png",
        role: "Damage"
    }, {
        name: "Brigitte",
        imageSrc: "./characters/images/brigitte.png",
        role: "Support"
    }, {
        name: "Cassidy",
        imageSrc: "./characters/images/cassidy.png",
        role: "Damage"
    }, {
        name: "Doomfist",
        imageSrc: "./characters/images/doomfist.png",
        role: "Tank"
    }, {
        name: "D.Va",
        imageSrc: "./characters/images/dva.png",
        role: "Tank"
    }, {
        name: "Echo",
        imageSrc: "./characters/images/echo.png",
        role: "Damage"
    }, {
        name: "Genji",
        imageSrc: "./characters/images/genji.png",
        role: "Damage"
    }, {
        name: "Hanzo",
        imageSrc: "./characters/images/hanzo.png",
        role: "Damage"
    }, {
        name: "Illari",
        imageSrc: "./characters/images/illari.png",
        role: "Support"
    }, {
        name: "Junker Queen",
        imageSrc: "./characters/images/junkerqueen.png",
        role: "Tank"
    }, {
        name: "Junkrat",
        imageSrc: "./characters/images/junkrat.png",
        role: "Damage"
    }, {
        name: "Kiriko",
        imageSrc: "./characters/images/kiriko.png",
        role: "Support"
    }, {
        name: "Lifeweaver",
        imageSrc: "./characters/images/lifeweaver.png",
        role: "Support"
    }, {
        name: "Lúcio",
        imageSrc: "./characters/images/lucio.png",
        role: "Support"
    }, {
        name: "Mei",
        imageSrc: "./characters/images/mei.png",
        role: "Damage"
    }, {
        name: "Mercy",
        imageSrc: "./characters/images/mercy.png",
        role: "Support"
    }, {
        name: "Moira",
        imageSrc: "./characters/images/moira.png",
        role: "Support"
    }, {
        name: "Orisa",
        imageSrc: "./characters/images/orisa.png",
        role: "Tank"
    }, {
        name: "Pharah",
        imageSrc: "./characters/images/pharah.png",
        role: "Damage"
    }, {
        name: "Ramattra",
        imageSrc: "./characters/images/ramattra.png",
        role: "Damage"
    }, {
        name: "Reaper",
        imageSrc: "./characters/images/reaper.png",
        role: "Damage"
    }, {
        name: "Reinhardt",
        imageSrc: "./characters/images/reinhardt.png",
        role: "Tank"
    }, {
        name: "Roadhog",
        imageSrc: "./characters/images/roadhog.png",
        role: "Tank"
    }, {
        name: "Sigma",
        imageSrc: "./characters/images/sigma.png",
        role: "Tank"
    }, {
        name: "Sojourn",
        imageSrc: "./characters/images/sojourn.png",
        role: "Damage"
    }, {
        name: "Soldier: 76",
        imageSrc: "./characters/images/soldier76.png",
        role: "Damage"
    }, {
        name: "Sombra",
        imageSrc: "./characters/images/sombra.png",
        role: "Damage"
    }, {
        name: "Symmetra",
        imageSrc: "./characters/images/symmetra.png",
        role: "Damage"
    }, {
        name: "Torbjörn",
        imageSrc: "./characters/images/torbjorn.png",
        role: "Damage"
    }, {
        name: "Tracer",
        imageSrc: "./characters/images/tracer.png",
        role: "Damage"
    }, {
        name: "Widowmaker",
        imageSrc: "./characters/images/widowmaker.png",
        role: "Damage"
    }, {
        name: "Winston",
        imageSrc: "./characters/images/winston.png",
        role: "Tank"
    }, {
        name: "Wrecking Ball",
        imageSrc: "./characters/images/wreckingball.png"
    }, {
        name: "Zarya",
        imageSrc: "./characters/images/zarya.png",
        role: "Tank"
    }, {
        name: "Zenyatta",
        imageSrc: "./characters/images/zenyatta.png",
        role: "Support"
    }
]