export const characters = [
    {
        name: "Ana",
        image: "./characters/images/ana.png",
        role: "Support"
    }, {
        name: "Ashe",
        image: "./characters/images/ashe.png",
        role: "Damage"
    }, {
        name: "Baptiste",
        image: "./characters/images/baptiste.png",
        role: "Support"
    }, {
        name: "Bastion",
        image: "./characters/images/bastion.png",
        role: "Damage"
    }, {
        name: "Brigitte",
        image: "./characters/images/brigitte.png",
        role: "Support"
    }, {
        name: "Cassidy",
        image: "./characters/images/cassidy.png",
        role: "Damage"
    }, {
        name: "Doomfist",
        image: "./characters/images/doomfist.png",
        role: "Tank"
    }, {
        name: "D.Va",
        image: "./characters/images/dva.png",
        role: "Tank"
    }, {
        name: "Echo",
        image: "./characters/images/echo.png",
        role: "Damage"
    }, {
        name: "Genji",
        image: "./characters/images/genji.png",
        role: "Damage"
    }, {
        name: "Hanzo",
        image: "./characters/images/hanzo.png",
        role: "Damage"
    }, {
        name: "Illari",
        image: "./characters/images/illari.png",
        role: "Support"
    }, {
        name: "Junker Queen",
        image: "./characters/images/junkerqueen.png",
        role: "Tank"
    }, {
        name: "Junkrat",
        image: "./characters/images/junkrat.png",
        role: "Damage"
    }, {
        name: "Kiriko",
        image: "./characters/images/kiriko.png",
        role: "Support"
    }, {
        name: "Lifeweaver",
        image: "./characters/images/lifeweaver.png",
        role: "Support"
    }, {
        name: "Lúcio",
        image: "./characters/images/lucio.png",
        role: "Support"
    }, {
        name: "Mei",
        image: "./characters/images/mei.png",
        role: "Damage"
    }, {
        name: "Mercy",
        image: "./characters/images/mercy.png",
        role: "Support"
    }, {
        name: "Moira",
        image: "./characters/images/moira.png",
        role: "Support"
    }, {
        name: "Orisa",
        image: "./characters/images/orisa.png",
        role: "Tank"
    }, {
        name: "Pharah",
        image: "./characters/images/pharah.png",
        role: "Damage"
    }, {
        name: "Ramattra",
        image: "./characters/images/ramattra.png",
        role: "Damage"
    }, {
        name: "Reaper",
        image: "./characters/images/reaper.png",
        role: "Damage"
    }, {
        name: "Reinhardt",
        image: "./characters/images/reinhardt.png",
        role: "Tank"
    }, {
        name: "Roadhog",
        image: "./characters/images/roadhog.png",
        role: "Tank"
    }, {
        name: "Sigma",
        image: "./characters/images/sigma.png",
        role: "Tank"
    }, {
        name: "Sojourn",
        image: "./characters/images/sojourn.png",
        role: "Damage"
    }, {
        name: "Soldier: 76",
        image: "./characters/images/soldier76.png",
        role: "Damage"
    }, {
        name: "Sombra",
        image: "./characters/images/sombra.png",
        role: "Damage"
    }, {
        name: "Symmetra",
        image: "./characters/images/symmetra.png",
        role: "Damage"
    }, {
        name: "Torbjörn",
        image: "./characters/images/torbjorn.png",
        role: "Damage"
    }, {
        name: "Tracer",
        image: "./characters/images/tracer.png",
        role: "Damage"
    }, {
        name: "Widowmaker",
        image: "./characters/images/widowmaker.png",
        role: "Damage"
    }, {
        name: "Winston",
        image: "./characters/images/winston.png",
        role: "Tank"
    }, {
        name: "Wrecking Ball",
        image: "./characters/images/wreckingball.png"
    }, {
        name: "Zarya",
        image: "./characters/images/zarya.png",
        role: "Tank"
    }, {
        name: "Zenyatta",
        image: "./characters/images/zenyatta.png",
        role: "Support"
    }
]